// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/prd-vibes/DarkTerminal.tsx": () => import("../components/mockups/prd-vibes/DarkTerminal.tsx"),
  "./components/mockups/prd-vibes/SoftModern.tsx": () => import("../components/mockups/prd-vibes/SoftModern.tsx"),
  "./components/mockups/prd-vibes/WarmEditorial.tsx": () => import("../components/mockups/prd-vibes/WarmEditorial.tsx")
};
